/*
    Para mais informações de como efetuar a correta configuração desse arquivo,
    consulte a documentação oficial da Sankkhya no link abaixo:
    <a href="https://developer.sankhya.com.br/docs/03_conf_addonstudio"/>
 */

// Nome provisório e exclusivo do add-on da Facilita.
rootProject.name = 'facilita-apuracao-fatura-addon'
include 'model'
include 'vc'
